[Component]
    Components = [
         { Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Purchase Processing.Cart Service.cartservice", Application = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;Labor Day Sale;1.2.10.0"}
    ]    
    Version = "1.2.2"
    CustomAction = "chart/cartservice"
    DockerRepo = "quay.io/hipsterstore/cartservice"
    GitUrl = "https://github.com/ortelius/store-cartservice"
    CustomAction = "GLOBAL.HelmChart"