
version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  deployhub-orb: deployhub/deployhub-orb@1.64.0

jobs:
  build-push-dh-update:
    executor: docker/docker
    steps:
      - setup_remote_docker 
      - checkout
      - docker/check
      - run:
          command: |
            docker create -v /home/circleci/project --name envscript quay.io/deployhub/compupdate:latest /bin/true;
            docker cp cloudbuild.toml envscript:/home/circleci/project/envvars.toml;
            docker run --volumes-from envscript quay.io/deployhub/compupdate:latest envscript --envvars /home/circleci/project/envvars.toml --envvars_sh /home/circleci/project/bash_env.sh;
            docker cp envscript:/home/circleci/project/bash_env.sh /tmp/bash_env.sh;
            docker cp envscript:/home/circleci/project/APPLIST /home/circleci/project/APPLIST;
            cat /tmp/bash_env.sh >> $BASH_ENV;
            cat /home/circleci/project/APPLIST;
            echo "######";
            cat APPLIST
      - run:
          command: |
            echo export IMAGE_TAG=\"$CIRCLE_BRANCH-v$COMPONENT_VERSION.$(git rev-list --count $CIRCLE_BRANCH)-g$(echo $CIRCLE_SHA1 | cut -b 1-8)\" >> $BASH_ENV  
      - docker/build:
          image: deployhub/store-cartservice
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: deployhub/store-cartservice
          tag: latest
      - run:
          command: |
            env | sort && echo "Digest is: $(</tmp/digest.txt)"
      - deployhub-orb/microservice_version_update:
              application: "@APPLIST"
              appversion: ""
              compname: $COMPONENT_NAME
              compversion: $IMAGE_TAG
              comptype: --docker
              helmchart: $COMPONENT_HELMCHART
              dockersha: $(</tmp/digest.txt)
              dockerrepo: $COMPONENT_DOCKERREPO
              builddate:  $(date)
              gitrepo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
              giturl: $CIRCLE_REPOSITORY_URL
              gitcommit: $CIRCLE_SHA1
              buildid: $CIRCLE_BUILD_URL
              buildnumber: $CIRCLE_BUILD_NUM
  
workflows:
  on-commit:
    jobs:
      - build-push-dh-update
      