
version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  deployhub-orb: deployhub/deployhub-orb@1.53.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: deployhub/store-cartservice
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: deployhub/store-cartservice
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      - deployhub-orb/compupdate:
              dhuser: admin
              dhpass: admin
              dhurl: http://exchange.openmakesoftware.com:8080
              application: Uptime War for Tomcat;14  
  
workflows:
  build-push-dh-update:
    jobs:
      - build-and-push
      