
version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  deployhub-orb: deployhub/deployhub-orb@1.74.0

jobs:
  build-push-dh-update:
    executor: docker/docker
    environment: 
      COMPONENT_NAME: GLOBAL.SF Tech.Online Store Company.Purchase Processing.Cart Service.cartservice
      COMPONENT_VERSION: 1.2.2
      COMPONENT_CHARTNAME: chart/cartservice
      COMPONENT_CUSTOMACTION: GLOBAL.HelmChart
      COMPONENT_DOCKERREPO: quay.io/hipsterstore/cartservice
      COMPONENT_IMAGENAME: hipsterstore/cartservice
      SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
      IMAGE_TAG: $(echo v$COMPONENT_VERSION.<< pipeline.number >>-g$SHORT_GIT_HASH)
    steps:
      - setup_remote_docker 
      - checkout
      - docker/check
      - run:
          name: Login to Quay
          command: docker login -u=$QUAY_USERNAME -p=$QUAY_PASSWORD quay.io
      - docker/build:
          image: $COMPONENT_IMAGENAME
          registry: quay.io
          tag: $IMAGE_TAG
      - docker/push:
          image: $COMPONENT_IMAGENAME
          registry: quay.io
          digest-path: /tmp/digest.txt
          tag: $IMAGE_TAG
      - run:
          command: |
            env | sort && echo "Digest is: $(</tmp/digest.txt)"
      - deployhub-orb/microservice_version_update:
              application: $COMPONENT_APPLICATION
              compname: $COMPONENT_NAME
              compversion: $IMAGE_TAG
              comptype: --docker
              helmchart: $COMPONENT_CHARTNAME
              dockersha: $(</tmp/digest.txt)
              dockerrepo: $COMPONENT_DOCKERREPO
              dockertag: $IMAGE_TAG
              builddate:  $(date)
              gitrepo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
              giturl: $CIRCLE_REPOSITORY_URL
              gitcommit: $CIRCLE_SHA1
              gitbranch: $CIRCLE_BRANCH
              gittag: "$CIRCLE_TAG"
              buildid: $CIRCLE_BUILD_NUM
              buildurl: $CIRCLE_BUILD_URL
              buildnumber: $CIRCLE_BUILD_NUM
              customaction: $COMPONENT_CUSTOMACTION
              preaction: ""
              postaction: "" 
workflows:
  on-commit:
    jobs:
      - build-push-dh-update:
          context: sharedvars 
      