
version: 2.1

orbs:
  docker: circleci/docker@0.5.20

jobs:
  build-push-dh-update:
    machine: true
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: deployhub/store-cartservice
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: deployhub/store-cartservice
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      - run:
          command: >
            docker run quay.io/deployhub/compupdate:latest
            compupdate
            --dhuser ${DH_USERID}
            --dhpass ${DH_PASSWORD}
            --dhurl ${DH_SERVERURL}
            --appname "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale
            --appversion "1.2.9.1"
            --compname "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.cartservice"
            --compversion "v0.1.1-4-g$CIRCLE_SHA1"
            --docker
            --compattr "GitCommit:${CIRCLE_SHA1}" 
            --compattr "GitUrl:${CIRCLE_REPOSITORY_URL}" 
            --compattr "GitRepo:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" 
            --compattr "Chart:helm/cartservice"
            --compattr "DockerSha:$(</tmp/digest.txt)"
            --compattr "DockerBuildDate:$(date)"
            --compattr "DockerRepo:deployhub/store-cartservice"
            --compattr "BuildId:${CIRCLE_BUILD_URL}"
            --compattr "BuildNumber:${CIRCLE_BUILD_NUM}"
  
workflows:
  on-commit:
    jobs:
      - build-push-dh-update
      