
version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  deployhub-orb: deployhub/deployhub-orb@1.66.0

jobs:
  build-push-dh-update:
    executor: docker/docker
    steps:
      - setup_remote_docker 
      - checkout
      - docker/check
      - deployhub-orb/envscript:
          envvars: cloudbuild.toml
          envvars_sh: $BASH_ENV
      - run:
          command: |
            echo export IMAGE_TAG=\"$CIRCLE_BRANCH-v$COMPONENT_VERSION.$(git rev-list --count $CIRCLE_BRANCH)-g$(echo $CIRCLE_SHA1 | cut -b 1-8)\" >> $BASH_ENV  
      - docker/build:
          image: deployhub/store-cartservice
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: deployhub/store-cartservice
          tag: latest
      - run:
          command: |
            env | sort && echo "Digest is: $(</tmp/digest.txt)"
      - deployhub-orb/microservice_version_update:
              application: $COMPONENT_APPLICATION
              compname: $COMPONENT_NAME
              compversion: $IMAGE_TAG
              comptype: --docker
              helmchart: $COMPONENT_HELMCHART
              dockersha: $(</tmp/digest.txt)
              dockerrepo: $COMPONENT_DOCKERREPO
              builddate:  $(date)
              gitrepo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
              giturl: $CIRCLE_REPOSITORY_URL
              gitcommit: $CIRCLE_SHA1
              gitbranch: $CIRCLE_BRANCH
              gittag: "$CIRCLE_TAG"
              buildid: $CIRCLE_BUILD_URL
              buildnumber: $CIRCLE_BUILD_NUM
  
workflows:
  on-commit:
    jobs:
      - build-push-dh-update
      