
version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  deployhub-orb: deployhub/deployhub-orb@1.77.0

jobs:
  build-push-dh-update:
    executor: docker/docker
    environment: 
      COMPONENT_NAME: GLOBAL.SF Tech.Online Store Company.Purchase Processing.Cart Service.cartservice
      COMPONENT_VERSION: 1.2.2
      COMPONENT_CHARTNAME: chart/cartservice
      COMPONENT_IMAGENAME: hipsterstore/cartservice
    steps:
      - setup_remote_docker 
      - checkout
      - docker/check:
          registry: $DOCKER_REGISTRY
      - run:
          name: Image tag
          command: echo export IMAGE_TAG=\"v${COMPONENT_VERSION}.${CIRCLE_BUILD_NUM}-g$(echo $CIRCLE_SHA1 | cut -c -7)\" >> $BASH_ENV
      - docker/build:
          registry: $DOCKER_REGISTRY
          image: $COMPONENT_IMAGENAME
          tag: $IMAGE_TAG
      - docker/push:
          registry: $DOCKER_REGISTRY
          image: $COMPONENT_IMAGENAME
          tag: $IMAGE_TAG
          digest-path: /tmp/digest.txt
      - deployhub-orb/microservice_version_update:
          registry: $DOCKER_REGISTRY
          image: $COMPONENT_IMAGENAME
          tag: $IMAGE_TAG
          helmchart: $COMPONENT_CHARTNAME
          compname: $COMPONENT_NAME
          compversion: $IMAGE_TAG
      - deployhub-orb/deploy_component:
          compname: $COMPONENT_NAME
          compversion: $IMAGE_TAG
workflows:
  on-commit:
    jobs:
      - build-push-dh-update:
          context: sharedvars 