apiVersion: v1
kind: Service
metadata:
  name: {{ include "cartservice.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "cartservice.name" . }}
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070